USE anhandforhumanityDB;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- $$$$$$\                                         $$\                                    $$\                                         $$\                     $$\ 
-- \_$$  _|                                        \__|                                   $$ |                                        $$ |                    \__|
--   $$ |  $$$$$$$\   $$$$$$$\  $$$$$$\   $$$$$$\  $$\ $$$$$$\$$$$\   $$$$$$\  $$$$$$$\ $$$$$$\    $$$$$$\        $$\    $$\ $$$$$$\  $$ | $$$$$$\   $$$$$$\  $$\ 
--   $$ |  $$  __$$\ $$  _____|$$  __$$\ $$  __$$\ $$ |$$  _$$  _$$\ $$  __$$\ $$  __$$\\_$$  _|  $$  __$$\       \$$\  $$  |\____$$\ $$ |$$  __$$\ $$  __$$\ $$ |
--   $$ |  $$ |  $$ |\$$$$$$\  $$$$$$$$ |$$ |  \__|$$ |$$ / $$ / $$ |$$$$$$$$ |$$ |  $$ | $$ |    $$ /  $$ |       \$$\$$  / $$$$$$$ |$$ |$$ /  $$ |$$ |  \__|$$ |
--   $$ |  $$ |  $$ | \____$$\ $$   ____|$$ |      $$ |$$ | $$ | $$ |$$   ____|$$ |  $$ | $$ |$$\ $$ |  $$ |        \$$$  / $$  __$$ |$$ |$$ |  $$ |$$ |      $$ |
-- $$$$$$\ $$ |  $$ |$$$$$$$  |\$$$$$$$\ $$ |      $$ |$$ | $$ | $$ |\$$$$$$$\ $$ |  $$ | \$$$$  |\$$$$$$  |         \$  /  \$$$$$$$ |$$ |\$$$$$$  |$$ |      $$ |
-- \______|\__|  \__|\_______/  \_______|\__|      \__|\__| \__| \__| \_______|\__|  \__|  \____/  \______/           \_/    \_______|\__| \______/ \__|      \__|
-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                                                                                                               


INSERT INTO Nazioni (nazione) VALUES
('Andorra'),
('United Arab Emirates'),
('Afghanistan'),
('Antigua and Barbuda'),
('Anguilla'),
('Albania'),
('Armenia'),
('Angola'),
('Antarctica'),
('Argentina'),
('American Samoa'),
('Austria'),
('Australia'),
('Aruba'),
('aland'),
('Azerbaijan'),
('Bosnia and Herzegovina'),
('Barbados'),
('Bangladesh'),
('Belgium'),
('Burkina Faso'),
('Bulgaria'),
('Bahrain'),
('Burundi'),
('Benin'),
('Saint Barthelemy'),
('Bermuda'),
('Brunei'),
('Bolivia'),
('Bonaire'),
('Brazil'),
('Bahamas'),
('Bhutan'),
('Bouvet Island'),
('Botswana'),
('Belarus'),
('Belize'),
('Canada'),
('Cocos [Keeling] Islands'),
('Democratic Republic of the Congo'),
('Central African Republic'),
('Republic of the Congo'),
('Switzerland'),
('Ivory Coast'),
('Cook Islands'),
('Chile'),
('Cameroon'),
('China'),
('Colombia'),
('Costa Rica'),
('Cuba'),
('Cape Verde'),
('Curacao'),
('Christmas Island'),
('Cyprus'),
('Czech Republic'),
('Germany'),
('Djibouti'),
('Denmark'),
('Dominica'),
('Dominican Republic'),
('Algeria'),
('Ecuador'),
('Estonia'),
('Egypt'),
('Western Sahara'),
('Eritrea'),
('Spain'),
('Ethiopia'),
('Finland'),
('Fiji'),
('Falkland Islands'),
('Micronesia'),
('Faroe Islands'),
('France'),
('Gabon'),
('United Kingdom'),
('Grenada'),
('Georgia'),
('French Guiana'),
('Guernsey'),
('Ghana'),
('Gibraltar'),
('Greenland'),
('Gambia'),
('Guinea'),
('Guadeloupe'),
('Equatorial Guinea'),
('Greece'),
('South Georgia and the South Sandwich Islands'),
('Guatemala'),
('Guam'),
('Guinea-Bissau'),
('Guyana'),
('Hong Kong'),
('Heard Island and McDonald Islands'),
('Honduras'),
('Croatia'),
('Haiti'),
('Hungary'),
('Indonesia'),
('Ireland'),
('Israel'),
('Isle of Man'),
('India'),
('British Indian Ocean Territory'),
('Iraq'),
('Iran'),
('Iceland'),
('Italy'),
('Jersey'),
('Jamaica'),
('Jordan'),
('Japan'),
('Kenya'),
('Kyrgyzstan'),
('Cambodia'),
('Kiribati'),
('Comoros'),
('Saint Kitts and Nevis'),
('North Korea'),
('South Korea'),
('Kuwait'),
('Cayman Islands'),
('Kazakhstan'),
('Laos'),
('Lebanon'),
('Saint Lucia'),
('Liechtenstein'),
('Sri Lanka'),
('Liberia'),
('Lesotho'),
('Lithuania'),
('Luxembourg'),
('Latvia'),
('Libya'),
('Morocco'),
('Monaco'),
('Moldova'),
('Montenegro'),
('Saint Martin'),
('Madagascar'),
('Marshall Islands'),
('Macedonia'),
('Mali'),
('Myanmar [Burma]'),
('Mongolia'),
('Macao'),
('Northern Mariana Islands'),
('Martinique'),
('Mauritania'),
('Montserrat'),
('Malta'),
('Mauritius'),
('Maldives'),
('Malawi'),
('Mexico'),
('Malaysia'),
('Mozambique'),
('Namibia'),
('New Caledonia'),
('Niger'),
('Norfolk Island'),
('Nigeria'),
('Nicaragua'),
('Netherlands'),
('Norway'),
('Nepal'),
('Nauru'),
('Niue'),
('New Zealand'),
('Oman'),
('Panama'),
('Peru'),
('French Polynesia'),
('Papua New Guinea'),
('Philippines'),
('Pakistan'),
('Poland'),
('Saint Pierre and Miquelon'),
('Pitcairn Islands'),
('Puerto Rico'),
('Palestine'),
('Portugal'),
('Palau'),
('Paraguay'),
('Qatar'),
('Reunion'),
('Romania'),
('Serbia'),
('Russia'),
('Rwanda'),
('Saudi Arabia'),
('Solomon Islands'),
('Seychelles'),
('Sudan'),
('Sweden'),
('Singapore'),
('Saint Helena'),
('Slovenia'),
('Svalbard and Jan Mayen'),
('Slovakia'),
('Sierra Leone'),
('San Marino'),
('Senegal'),
('Somalia'),
('Suriname'),
('South Sudan'),
('Sao Tome and Principe'),
('El Salvador'),
('Sint Maarten'),
('Syria'),
('Swaziland'),
('Turks and Caicos Islands'),
('Chad'),
('French Southern Territories'),
('Togo'),
('Thailand'),
('Tajikistan'),
('Tokelau'),
('East Timor'),
('Turkmenistan'),
('Tunisia'),
('Tonga'),
('Turkey'),
('Trinidad and Tobago'),
('Tuvalu'),
('Taiwan'),
('Tanzania'),
('Ukraine'),
('Uganda'),
('U.S. Minor Outlying Islands'),
('United States'),
('Uruguay'),
('Uzbekistan'),
('Vatican City'),
('Saint Vincent and the Grenadines'),
('Venezuela'),
('British Virgin Islands'),
('U.S. Virgin Islands'),
('Vietnam'),
('Vanuatu'),
('Wallis and Futuna'),
('Samoa'),
('Kosovo'),
('Yemen'),
('Mayotte'),
('South Africa'),
('Zambia'),
('Zimbabwe');

INSERT INTO Mansioni (descrizione, dataInizio, dataFine, idNazione, provincia, citta, CAP, via, nCivico) VALUES
('soup kitchen', '2013-01-01', '2013-01-02', 51, 'Artemisa', 'Bauta', NULL, NULL, NULL),
('soup kitchen', '2014-05-01', '2014-05-6', 102, 'Leinster', 'Dublino', NULL, NULL, NULL),
('wetland restoration', '2015-01-20', '2015-03-15', 59, 'Copenaghen', 'Copenaghen', NULL, NULL, NULL),
('Water distribution Africa', '2013-01-01', '2013-02-01', 47, 'Camerun', 'Yaounde', NULL, NULL, NULL);

INSERT INTO Sedi (nome, idNazione, provincia, citta, CAP, via, telefono, email) VALUES
('una mano per l\'umanita\'', 110, 'Frosinone', 'Atina', '03042', 'Via dei Sanniti', '0776443221', 'atina_it@anhandforhumanity.org'),
('una mano para la humanidad', 68, 'Asturie', 'Oviedo', NULL, 'via de la murte', '0223443221', 'oviedo_sp@anhandforhumanity.org'),
('i ka lima no ka mea', 233, 'Hawaii', 'Honolulu', NULL, 'Halemanu st', '022143221', 'honolulu_usa@anhandforhumanity.org'),
('an hand for humanity', 233, 'Alaska', 'Juneau', NULL, 'cold st', '099143221', 'alaska_usa@anhandforhumanity.org');

INSERT INTO Personale (cod, nome, cognome, dataNascita, LuogoNascita, nDocumento, idNazione, provincia, citta, telefono, email, pass, descrizioneQualifiche, ruolo, stipendioNominale) VALUES
('P1', 'Pippo', 'Laurenti', '1985-01-01', 'Sora', 'AS444R', 110, 'Frosinone', 'Sora', '99933044', 'pippo.laurenti@gmail.com', 'trottolino','diploma in biologia, laurea in biologia', 'personale', 1200),
('P2', 'Tonio', 'Cartonio', '1970-12-23', 'Cassino', 'AS655R', 110, 'Frosinone', 'Alvito', '8893244', 'tonio.cartonio@libero.it', 'ciccino', 'diploma in ragioneria, laurea in economia', 'tesoriere', 1300),
('P3', 'Pasquale', 'Benedetti', '2000-06-01', 'Atina', 'AS635R', 110, 'Frosinone', 'Casalattico', '8223244', 'pbenedetti@gmail.com', 'ciccetto', 'licenza media', 'amministratore', 1500),

('P4', 'Antonio', 'Banderas', '1985-01-01', 'Oviedo', 'SF121V', 68, 'Asturie', 'Oviedo', '8232244', 'a_banderas@hotmail.com', 'rosita', 'diploma istituto tecnico, laurea in recitazione drammatica', 'amministratore', 1450),
('P5', 'Penelope', 'Cruz', '1960-07-22', 'Oviedo', 'SF123V', 68, 'Asturie', 'Oviedo', '82377744', 'cruz.penelope@gmail.com', 'rosetta', 'diploma liceo classico, laurea in recitazione drammatica', 'tesoriere', 1350),
('P6', 'Fulvios', 'Rodriguez', '1995-06-30', 'Oviedo', 'SF333V', 68, 'Asturie', 'Oviedo', '82377554', 'frod@gmail.com', 'rosalinda', 'diploma istituto tecnico', 'personale', 1250),

('P7', 'Chin', 'O\'Kelly', '1990-10-02', 'Honolulu', 'HH897S', 233, 'Hawaii', 'Honolulu', '8000044', 'chino@apple.me', 'aloha', 'diploma liceo scientifico, scuola di polizia', 'personale', 1600),
('P8', 'Kono', 'kalakaua', '1955-09-05', 'Honolulu', 'HH844S', 233, 'Hawaii', 'Honolulu', '8111144', 'konokalakaua@yahoo.com', 'alohaola', 'diploma liceo classico', 'tesoriere', 1800),
('P9', 'Kame', 'Kona', '1985-01-06', 'Honolulu', 'HH999S', 233, 'Hawaii', 'Honolulu', '8222244', 'kamekona@yahoo.com', 'alohaolaola', 'diploma alberghiero', 'amministratore', 1600),

('P10', 'Danny', 'Williams', '1991-04-16', 'Juneau', 'AA344F', 233, 'Alaska', 'Juneau', '9667788', 'danno@apple.me', 'cold', 'licensa media', 'tesoriere', 600),
('P11', 'Steven', 'Seguall', '1976-05-22', 'Juneau', 'AA366F', 233, 'Alaska', 'Juneau', '9669988', 'stevs@gmail.com', 'verycold', 'licensa media, attestato istruttore arti marziali', 'personale', 600),
('P12', 'Jean Claude', 'Van Damme', '1984-08-18', 'Juneau', 'AA388F', 233, 'Alaska', 'Juneau', '9897788', 'jcvd@yahoo.com', 'veryverycold', 'diploma alberghiero', 'amministratore', 600);

INSERT INTO Impiegato (codPersonale, idSede, trasferta, dataInizio, dataFine) VALUE
('P1', 1, 0, '2002-04-09', NULL),
('P1', 3, 1, '2004-04-09', '2004-05-10'),
('P1', 3, 1, '2006-07-08', '2007-05-10'),
('P2', 1, 0, '2001-07-08', NULL),
('P3', 3, 0, '2010-12-03', '2015-10-16'),
('P2', 1, 1, '2009-12-03', '2010-10-16'),
('P3', 3, 1, '2012-04-02', '2012-07-06'),
('P7', 4, 0, '2012-04-02', NULL),
('P7', 3, 1, '2013-06-22', NULL);


INSERT INTO DitteEsterne (cod, ragioneSociale, sitoWeb, telefono, email) VALUES
('D1', 'Lete', 'www.lete.it', '07753323', 'contatti@lete.it'),
('D2', 'Decathlon', 'www.Decathlon.com', '05454322', 'contact@decathlon.com'),
('D3', 'IKEA', 'www.ikea.se', '02222333', 'contact@ikea.se');

INSERT INTO Partner (cod, nome, sitoWeb) VALUES
('PA1', 'WWF', 'www.wwf.org'),
('PA2', 'unicef', 'www.unicef.org'),
('PA3', 'greenpace', 'www.greenpace.org');

INSERT INTO Civili (cod, nome, cognome, dataNascita, luogoNascita, nDocumento, idNazione, telefono, email, pass) VALUES
('C1', 'Geltrude', 'Tommaselli', '1972-05-22', 'Pisa', 'FF452', 110, '4443332', 'ger.tom@libero.it', '1234'),
('C2', 'Danny', 'Trejo', '1963-08-23', 'Mexico City', 'FF222', 233, '44455532', 'machete@gmail.com', 'asd123'),
('C3', 'Chuck', 'Norris', '1954-02-02', 'Houston', 'CN452', 110, '4443332', 'chuck.norris@chuck.norris', 'chucknorris');

INSERT INTO MovimentiBancari (descrizione, importo, giorno, momento, codTesoriere, codCollaboratore) VALUES
('salary payment', -1200, '2016-01-01', '14:40:32', 'P2', 'P1'),
('salary payment in transfer', -1250, '2006-08-08', '14:32:55', 'P2', 'P1'),
('salary payment in transfer', -1300, '2007-01-21', '14:54:12', 'P2', 'P1'),
('salary payment', -1400, '2015-07-01', '12:54:12', 'P2', 'P2'),
('salary payment', -1300, '2016-04-01', '14:54:12', 'P2', 'P2'),
('salary payment', -1400, '2016-07-01', '14:54:12', 'P2', 'P2'),
('salary payment', -1400, '2017-07-01', '12:54:12', 'P2', 'P2'),
('salary payment', -1750, '2016-02-01', '14:54:12', 'P5', 'P6'),
('salary payment', -1300, '2016-01-01', '14:54:12', 'P5', 'P7'),
('salary payment', -1300, '2016-01-01', '14:54:12', 'P5', 'P7'),
('Contribution', -500, '2018-08-10', '11:40:32', 'P5', 'PA1'),
('Contribution', -500, '2018-08-11', '12:30:12', 'P5', 'PA1'),
('Contribution', -500, '2015-08-11', '12:30:12', 'P2', 'PA1'),
('Contribution', -500, '2018-08-11', '18:30:12', 'P2', 'PA1'),
('Contribution', 10200, '2018-08-08', '11:40:32', NULL, 'PA2'),
('anonymus donation', 1000, NULL, NULL, NULL, NULL),
('donation', 350, NULL, NULL, NULL, 'P6');

INSERT INTO Collabora(codCollaboratore, idMansione) VALUES
('P1',1),
('P3',1),
('D2',1),
('PA2',2),
('C3',2),
('D2',2);
